In [37]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', 50)
pd.options.mode.chained_assignment = None
np.random.seed(0)

In [38]:
df_specific = pd.read_csv("./data_wrangled/df_specific_wrangle.csv", encoding="utf-8")
df_specific.head()

대학코드                              대학명                                           gen_info                                           env_info                                          food_info                                         study_info                                        office_info                                         facil_info                                          mhct_info                                          help_info                                           etc_info
0  AR000004         Universidad del Salvador  아르헨티나의 대다수 대학교는 한국처럼 캠퍼스가 있는 것이 아니라 도시 내에 몇개의 ...  대학교가 도시 여러곳에 분포하고 있으므로 각기 다르다. 하지만 남녀를 불문하고 부에...  기숙사는 학교에서 제공하지 않고 두가지 옵션이 주어진다. 홈스테이 혹은 게스트 하우...  아르헨티나에서의 대학 수업은 주로 오전 혹은 저녁에 있다. 대부분의 학생들이 일을하...  EL SALVADOR대학교는 국제 교육부가 잘 되있는 학교이다. 아르헨티나 대학교들...  부대시설로는 헬스장이 있다고 알고 있으나 시내와 먼 곳에 있었다. 동아리는 몇가지 ...  딱히 컬쳐쇼크를 받을 만 한 요소는 없었던 것 같다. 하지만 처음에 언어적인 면에서...  살바도르 대학교 국제처에서 비자문제나 숙소문제(홈스테이경우) 등은 해결해 주고, 특...                                                NaN
1  AU000019   Australian National University  ANU has a very big campus, but unlike Yonsei, ...  The city center, called CIVIC, is 20min walk a...  There are many housing options, but I chose to...  In my personal opinions, classes are generally...  Overall, I did not have to ask for help much f...  There were many clubs for you to join at ANU, ...  I did have some culture shock during my first ...  I was helped a lot, especially during the firs...  Overall, my stay in Australia has been nothing...
2  AU000001                  Bond University  Bond대학교는 휴양지로 유명한 골드코스트에 위치해있습니다. 서퍼스 파라다이스, 브...  학교 주변은 조용하고 깨끗한 평화로운 전원마을의 느낌입니다. 학교에서 5분정도 걸어...  거주형태는 크게 On Campus와 Off Campus로 나뉩니다. 저는 기숙사에 ...  수업은 보통 4개의 수업을 듣습니다. 저는 Chinese1, Australian p...  교환생활 중 국제교육부와 연락할 일은 없었습니다. 교환학생을 가서 따로 국제교육부와...  학기초에 동아리 박람회식으로 여러 동아리들의 부스가 세워집니다. 관심 있는 동아리에...  특별히 culture shock이라기 보다는 정말 다양한 문화를 접하는 것 자체가 ...  수업관련해서는 교수님께 질문을 해도 친절하게 알려주시고, 또 교내에 과제나 발표준비...  Bond와 그 동네를 생각하면 여유롭고 평화로웠던 분위기가 아직도 생생해요. 여기서...
3  AU000002                Curtin University  크기는 연세대학교 정도의 크기를 가지고있으며, 버스를 타고 시티와 큼직큼직한 지역들...  학교주변에는 큰 마트가 2개있고 거기에 미용실,약국,아시안마트 등의 편의시설이 있다...  기숙사에 살면 다른 성(남자 여자)이 같이 한 하우스에 살며 친구처럼 지낸다. 기숙...  수업은 일반적으로 렉쳐형식의 수업1시간과 워크샵 형식의 튜토리얼2시간으로 구성된다....  NaN 국제학생이 많기 때문에 다양한 프로그램이 존재합니다.확인해보시고 원하시는 프...  동아리는 종류가 다양한데 들어가기위해서는 가입비를 내야한다. 신기한점으로는 학교내에...  한국이랑 똑같다. 그냥 다른사람들을 의식하지않은 문화. 모두 친절하고 정중해서 특별...  영어가 능숙하다면 국제처를 방문하는것을 추천. 하지만 영어가 부족하고 의사소통이 원...  93dbal@naver.com 비치(해변)가 정말 좋으니 꼭 두번 세번 여러번 가시...
4  AU000003  Curtin University of Technology  curtin university는 서호주 퍼스에 위치한 대학입니다. 퍼스는 서호주에...  커튼 주변에는 waterford plaza를 제외하고 별다른 것이 없습니다. 그러나...  erica underwood house 기숙사에서 지냈습니다. 전기세, 수도세, 인...  수업은 모두 전공 강의를 들어서 구체적으로 말할 수는 없지만 상대평가를 하는 우리 ...  교환학생을 위한 영어 프로그램이 국제교육부나 단대에 잘 마련되어있습니다. 대부분 영...  수업은 12주인데 1주씩 3번 쉬고, 시험기간이 2주입니다. 그래서 tuition ...  막상 호주에 오면 생각보다 인종차별이 심한 것 같기도 하지만 그래도 인종차별이 존재...  교환학생을 준비하면 커튼 study abroad에서 담당 선생님께 메일이 옵니다. ...  저는 동호주, 뉴질랜드로 여행을 갔다가 그쪽이 너무 좋아서 교환학생 국가로 호주를 ...

In [40]:
# increase length of pandas display to look at dataset
pd.set_option('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', 1000)
df_specific.iloc[110]

대학코드                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [36]:
df_specific.shape

(470, 11)

In [41]:
from konlpy.tag import Okt
twitter = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 normalization, stemming 처리하도록 함
# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 normalization, stemming 처리하도록 함
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [42]:
import re

def preprocessing(text):
    # 개행문자 제거
    text = re.sub('\\\\n', ' ', text)
    # 특수문자 제거
    # 특수문자나 이모티콘 등은 때로는 의미를 갖기도 하지만 여기에서는 제거했습니다.
    # text = re.sub('[?.,;:|\)*~`’!^\-_+<>@\#$%&-=#}※]', '', text)
    # 한글, 영문, 숫자만 남기고 모두 제거하도록 합니다.
    # text = re.sub('[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9]', ' ', text)
    # 한글, 영문만 남기고 모두 제거하도록 합니다.
    text = re.sub('[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z]', ' ', text)
    return text

In [44]:
%time rawdata = df_specific["gen_info"].apply(preprocessing)

CPU times: user 289 ms, sys: 9.71 ms, total: 299 ms
Wall time: 298 ms


In [45]:
print(rawdata)

  실내 온도는 잘 조절되기 때문에 무리 없이 있었습니다  몬트리올  보스턴  뉴욕 정도가 근교 비행기 없이 가능한 관광지라고 생각합니다  몬트리올이나 보스턴은 메가버스를 이용하면 아주 저렴해서 교환학생들끼리 엠티 가듯이 다녀오기도 했습니다 UVM은 큰 종합대학입니다 캠퍼스가 꽤 큰 편입니다  University of vermont는 버몬트주 벌링턴시에 위치하고 있으며  지리적으로 미국의 북동쪽에 위치하고 있습니다  vermont대학교에 교환학교를 신청하기 전까지는 버몬트주가 존재하고 있는지도 몰랐기에 많이 낯설었었습니다  아마 이 글을 읽는 많은 분들도 버몬트주에 대해서 잘 모르실 것이라고 생각합니다  버몬트주는 현재 미국 대선의 경선후보인 버니 샌더스가 십여년간 시장으로 있었던 곳이기도 한데요  이 곳의 사람들은 항상 배려넘치고  여유가 있었습니다  인종차별은 전혀 없었습니다  학교내의 인종은 백인이 약    정도 있는 것으로 보이며  중국인이     기타   가 있는 것으로 보입니다  원래는 중국인들이 많지 않았는데  버몬트대학교가 Global gateway program이라는 것을 시행하면서 많은 중국인들이 버몬트 대학교에 유입된 것으로 보입니다  한국 사람은 거의 없다고 보시면 됩니다  매학기에 교환학생으로 한국사람이    명이 온다고 알고 있는데  이번학    University of Vermont는 미국 북동부 버몬트 주에 위치하고 있습니다  버몬트 주는 캐나다 국경과 접해있어서 봄학기에 가시면 버몬트의 아름다운 겨울을 즐기실 수 있어요  비교적 길고 추운 겨울 덕분에 스키산업이 굉장히 발달해있고 낙농업과 맛있는 메이플 시럽이 유명하답니다  저는 봄학기에...
451    유덥이 연대보다 크기는 더 크지만  연대는 긴 모양인 반면 유덥은 좀 더 둥근 모양이고 캠퍼스 내에 시내버스가 다니기 때문에 돌아다니기는 더 편리합니다 유덥은 미국의 북서부 지역인 워싱턴주 시애틀에 위치해 있습니다  시애틀 시내까지 버스나 지하철을 타고      분 거리이며 교통

In [46]:
vectorize = TfidfVectorizer(
    tokenizer=tokenizer,
    min_df=5,
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)
%time X = vectorize.fit_transform(rawdata)

# fit_transform, (sentence 5, feature 7)

print(X.toarray())

# ([[0.        , 0.40824829, 0.81649658, 0.        , 0.        , 0.        , 0.40824829],
# [0.        , 0.40824829, 0.40824829, 0.        , 0.        , 0.        , 0.81649658],
# [0.41680418, 0.        , 0.        , 0.69197025, 0.41680418, 0.41680418, 0.        ],
# [0.76944707, 0.        , 0.        , 0.63871058, 0.        , 0.        , 0.        ],
# [0.        , 0.        , 0.        , 0.8695635 , 0.34918428, 0.34918428, 0.        ]])

# 문장에서 뽑아낸 feature 들의 배열
features = vectorize.get_feature_names()

CPU times: user 7min 1s, sys: 3.26 s, total: 7min 4s
Wall time: 4min 20s
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [47]:
print(len(features))

5479


In [48]:
features[:12]

['about',
 'abroad',
 'ac',
 'academic',
 'access',
 'accessible',
 'accounting',
 'acre',
 'acres',
 'across',
 'activities',
 'activity']

In [49]:
srch=[t for t in tokenizer('여유로운 교환학생 생활') if t in features]
print(srch)

['여유', '교환학생', '생활']


In [51]:
# dtm 에서 검색하고자 하는 feature만 뽑아낸다.
srch_dtm = np.asarray(X.toarray())[:, [
    # vectorize.vocabulary_.get 는 특정 feature 가 dtm 에서 가지고 있는 index값을 리턴한다
    vectorize.vocabulary_.get(i) for i in srch
]]

print(len(srch_dtm))
srch_dtm

470


array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.0151595 ],
       [0.04689854, 0.02849998, 0.04569745],
       ...,
       [0.        , 0.01583543, 0.01647499],
       [0.        , 0.13702356, 0.        ],
       [0.        , 0.        , 0.        ]])

In [52]:
score = srch_dtm.sum(axis=1)
score

array([0.        , 0.0151595 , 0.12109597, 0.0690816 , 0.06527516,
       0.08369999, 0.1132919 , 0.07921744, 0.07096675, 0.06665128,
       0.14530826, 0.02861837, 0.08699822, 0.        , 0.08943156,
       0.06678155, 0.08327949, 0.        , 0.        , 0.04221232,
       0.03824822, 0.03807513, 0.08149014, 0.        , 0.08430371,
       0.05768498, 0.04912686, 0.11156724, 0.05812688, 0.04232991,
       0.06709365, 0.05909656, 0.090612  , 0.        , 0.05569138,
       0.06213035, 0.08610457, 0.07812537, 0.11968985, 0.09418015,
       0.03545733, 0.        , 0.08263472, 0.08219678, 0.06415991,
       0.09084053, 0.        , 0.06787491, 0.10359659, 0.07532207,
       0.14214385, 0.        , 0.05528707, 0.11989254, 0.09040864,
       0.06452031, 0.05662489, 0.04162398, 0.07922159, 0.06538199,
       0.10869337, 0.        , 0.08075149, 0.        , 0.04801746,
       0.07097453, 0.10315266, 0.07768173, 0.        , 0.06624822,
       0.07067756, 0.08342355, 0.06067932, 0.        , 0.08218

In [53]:
for i in score.argsort()[::-1]:
    if score[i] > 0.053:
        print((df_specific["대학명"].iloc[i], score[i]))

('Elmhurst College', 0.1777110157796109)
('Akita International University', 0.15856239804899513)
('Universidad Nacional Autonoma de Mexico (UNAM)', 0.15849277030028788)
('The Hebrew University of Jerusalem', 0.1559267585923898)
('University of Adelaide', 0.14530825663755934)
('CSU Northridge', 0.14515601748341264)
('Nanjing University', 0.14214385438541746)
('Whitworth College', 0.1370235550485317)
('Columbia University', 0.13464089503805182)
('University of North Carolina at Greensboro', 0.13149668607315843)
('Tokyo Institute of Technology', 0.12885253123850388)
('Meiji Gakuin University', 0.12274818964914916)
('University of Brighton', 0.12265187524027586)
('Sophia University', 0.12126726719921749)
('Bond University', 0.12109597182600103)
('Shandong University', 0.11989254300563337)
('Kyoto University', 0.11985585871072149)
('University of Calgary', 0.11968985254628994)
('University of Oregon', 0.11841892196616122)
('Massey University (Auckland, Palmerston North, Wellington)', 0.1181